[package]
name = "greybound-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Greybound web app host using the shared iced UI."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1"
greybound = { path = "../core", default-features = false }
greybound-ui = { path = "../ui" }
iced = { version = "0.10", default-features = false, features = ["canvas", "image", "web-colors"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "AudioBuffer",
    "AudioContext",
    "AudioDestinationNode",
    "AudioNode",
    "AudioProcessingEvent",
    "console",
    "EventTarget",
    "MediaDevices",
    "MediaStream",
    "MediaStreamAudioSourceNode",
    "MediaStreamConstraints",
    "MediaStreamTrack",
    "Navigator",
    "ScriptProcessorNode",
    "Window"
] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
